/**
 * LAUNCH SPLASH — the choreography, as data.
 *
 * WHAT THIS OWNS
 *   Every number in the splash sequence, in one place, in milliseconds.
 *   The CSS reads them as custom properties; the hook reads them to know
 *   when the sequence is over. Neither hard-codes a duration.
 *
 * WHAT THIS MUST NEVER DO
 *   Contain behaviour. config/ is a dependency-free leaf (lint-enforced):
 *   data, never a conditional.
 *
 * ═══════════════════════════════════════════════════════════════════════
 * WHY A SPLASH EXISTS AT ALL, GIVEN WHAT src/index.css SAYS
 *
 * The motion block in index.css states that two animations exist in the
 * whole application, because "a financial interface that performs
 * undermines the trust its numbers are earning." That principle is intact
 * and still governs every screen. The splash is a deliberate, owner-
 * specified exception (D17): it plays before any number is on screen, so
 * it cannot decorate data or delay a reading of it.
 *
 * The line it must not cross: the splash never waits for data. It is a
 * fixed-length brand moment layered OVER an app that is booting normally
 * underneath it. If it ever became a loading gate, a slow network would
 * turn a 2-second animation into an indefinite one, and the app already
 * has skeletons for exactly that job.
 * ═══════════════════════════════════════════════════════════════════════
 *
 * THE SEQUENCE — Luxury Light Sweep
 *
 *   0ms      dark background; the mark is present but nearly unlit
 *   90ms     the sweep begins: a soft diagonal edge crosses the mark from
 *            lower-left to upper-right, with a specular band riding it
 *   990ms    the sweep has passed; the mark is fully lit
 *   700ms    a soft halo rises behind the mark, overlapping the sweep's tail
 *   1320ms   the halo settles to a faint resting glow — animation complete
 *   1620ms   hold ends
 *   2000ms   cross-fade to the application
 *
 * The sweep and the specular band share one duration and one easing curve
 * so the light sits exactly on the reveal edge instead of drifting off it.
 * Changing SWEEP_DURATION moves both, which is the point of them being here.
 */

/**
 * The splash background.
 *
 * DUPLICATION WARNING — this value is repeated verbatim by an inline
 * <style> in index.html and by `background_color` in the PWA manifest in
 * vite.config.js. Both copies are deliberate:
 *
 *   - the <style> must apply before first paint, or a dark-splash launch
 *     flashes the light canvas colour first; a stylesheet link is too late
 *     on a cold load and an inline script cannot import a module without
 *     becoming async
 *   - `background_color` is what Android paints for its own native splash
 *     BEFORE the web app runs at all. Left at the light canvas colour it
 *     produced a white flash, then a dark splash, on every launch
 *
 * `splashBootstrapContract()` exists so a test asserts all three stay in
 * step, rather than the drift being discovered as a flash on a phone.
 */
export const SPLASH_BACKGROUND = '#0b0f14';

/** The logo. Sized and generated by scripts/generate-icons.py. */
export const SPLASH_LOGO_SRC = '/brand/gati-splash.webp';

/**
 * Responsive logo size. One clamp, no breakpoints: the mark takes 28% of the
 * narrow axis on a phone, is capped by viewport height on a short landscape
 * window, and never exceeds 128px on a large monitor.
 *
 * Deliberately a `min()` of three terms rather than a media query, so
 * foldables and split-screen windows land somewhere sensible without any of
 * them having been enumerated.
 *
 * ═══════════════════════════════════════════════════════════════════════
 * WHY 28vw / 128px, AND NOT THE 56vw / 320px THIS USED TO BE.
 *
 * The old value put the mark at 56% OF THE SCREEN WIDTH on every phone —
 * 179px on an SE, 218px on an iPhone 14, 241px on a Pro Max. That is poster
 * scale, not launch scale, and the owner read it exactly that way.
 *
 * A launch mark is a signature, not an illustration. The apps this is
 * measured against sit at roughly a quarter to a third of the narrow axis:
 * on a 390pt phone Instagram is about 90pt, Airbnb about 100pt, most banking
 * apps 80–120pt. 28vw lands at 109pt there, and 90pt on a small phone.
 *
 * The 128px desktop cap is the same reasoning at the other end. Slack, VS
 * Code and Figma all show a ~128px mark on launch; at 320px the mark stopped
 * reading as a logo and started reading as artwork the user was meant to
 * look at, which is the opposite of a splash's job — to be noticed once and
 * then get out of the way.
 *
 * NOTHING ELSE NEEDS TOUCHING. Every layer of the composition — the halo's
 * `inset: -22%`, the glint band, the sweep window — is expressed as a
 * percentage of the stage, so the whole choreography scales from this one
 * value and its proportions are unchanged.
 * ═══════════════════════════════════════════════════════════════════════
 */
export const SPLASH_LOGO_SIZE = 'min(28vw, 22vh, 128px)';

/**
 * Every duration and delay, in milliseconds.
 *
 * Total to first frame of the app: DELAY + SWEEP + HOLD + FADE, with the
 * glow overlapping the sweep's tail rather than following it. The brief
 * says the animation itself should run 1.2–1.5s; it completes at 1320ms.
 */
export const SPLASH_TIMING = {
  /** A beat of pure darkness so the sweep reads as arriving, not as already underway. */
  sweepDelay: 90,
  /** The reveal edge and its specular band. The dominant motion. */
  sweepDuration: 900,
  /** The halo starts before the sweep ends, so light and glow are one gesture. */
  glowDelay: 700,
  glowDuration: 620,
  /** The finished mark, held still. */
  hold: 300,
  /** Cross-fade to the app. */
  fadeOut: 380,
};

/**
 * The reduced-motion sequence. Not a shortened version of the above — a
 * different, complete one: the mark simply appears, is held, and fades.
 * No sweep, no travelling light, no halo pulse.
 *
 * Nothing is lost, because the splash never carried information. It is
 * kept rather than skipped so a user who prefers reduced motion still
 * gets the same launch identity, without the movement.
 */
export const SPLASH_TIMING_REDUCED = {
  sweepDelay: 0,
  sweepDuration: 0,
  glowDelay: 0,
  glowDuration: 0,
  hold: 220,
  fadeOut: 300,
};

/**
 * Premium easing — a symmetric ease-in-out cubic.
 *
 * No overshoot and no elastic term anywhere in the splash: an overshoot is
 * a spring, a spring implies mass, and mass implies the interface is a
 * physical object. Light is not.
 */
export const SPLASH_EASING = 'cubic-bezier(0.65, 0, 0.35, 1)';

/**
 * When the whole sequence is finished, relative to mount.
 * @param {typeof SPLASH_TIMING} timing
 * @returns {number} milliseconds
 */
export function splashTotalDuration(timing) {
  const animationEnd = Math.max(
    timing.sweepDelay + timing.sweepDuration,
    timing.glowDelay + timing.glowDuration,
  );
  return animationEnd + timing.hold + timing.fadeOut;
}

/**
 * The moment the fade-out starts — i.e. when the app underneath begins to
 * become visible.
 * @param {typeof SPLASH_TIMING} timing
 * @returns {number} milliseconds
 */
export function splashFadeStart(timing) {
  return splashTotalDuration(timing) - timing.fadeOut;
}

/**
 * The exact values the inline <style> in index.html and the PWA manifest
 * must use. Compared against both by a test — see
 * config/__tests__/splash.test.js.
 */
export function splashBootstrapContract() {
  return {
    background: SPLASH_BACKGROUND,
    logoSrc: SPLASH_LOGO_SRC,
    attribute: 'data-splash',
    activeValue: 'active',
  };
}
